version: 2
jobs:
  build-snapshot:
    docker:
      - image: circleci/golang:1.14
    steps: # steps that comprise the `build` job
      - checkout
      - run: "curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh"
      - run: ./bin/goreleaser build --snapshot
  build-tag:
    docker:
      - image: circleci/golang:1.14
    steps: # steps that comprise the `build` job
      - checkout
      - run: "curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh"
      - run: ./bin/goreleaser build
      - run: ./bin/goreleaser release
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-snapshot:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
